### ISSUE TITLE
Oviyam on Synology docker

### ISSUE THREAD

**Issue by princdoberman** [leonardoforti/oviyam#1]
can you please explain to me how I can login at Oviyam ?
I install at my Synology docker and start Oviyam container and after that I got first login page where I can't log in.

**Comment by leonardoforti** [comment]
Hi! Coincidentally I was making some changes these days in the dockerfile and I have to resume development and modify the documentation...
The users are declared inside the tomcat-users.xml file, from there you can add or modify the ones you need. The default user is: admin and the password is: adm1n (yes, with a number "1" instead of the letter "i")
